platform :ios, '16.0'

def pods
  # Base
  # pod 'RxSwift', '6.5.11'
  # pod 'Swinject', '2.9.2'

  # Test spec
  pod 'TrailQuest', path: '../', :testspecs => ['Tests']

  # Common
end

target 'TrailQuestSandbox' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.5'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end
